### ISSUE TITLE
Unable to open save

### ISSUE THREAD

**Issue by Nayroy** [gibbed/Gibbed.BorderlandsOz#2]
---------------------------
Error
---------------------------
An exception was thrown (press Ctrl+C to copy):

System.NotImplementedException: don't know how to read stat type 49

   at Gibbed.BorderlandsOz.FileFormats.PlayerStats.ReadData(Stream input, DataType type, Endian endian)

   at Gibbed.BorderlandsOz.FileFormats.PlayerStats.Deserialize(Stream input, Endian endian)

   at Gibbed.BorderlandsOz.FileFormats.PlayerStats.Deserialize(Byte[] data, Endian endian)

   at Gibbed.BorderlandsOz.FileFormats.SaveFile.Deserialize(Stream input, Platform platform, DeserializeSettings settings)

   at Gibbed.BorderlandsOz.SaveEdit.ShellViewModel.<>c__DisplayClass58_0.<ReadSave>b__2()

   at Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context)
---------------------------
OK   
---------------------------
I am able to open other saves that are under level 30. The save that is giving me this error is at level cap.

**Comment by gibbed** [comment]
Could you attach that save file to this issue?

**Comment by Nayroy** [comment]
My save was able to be loaded when trying today, not sure what happened, but here's the save.

http://www.mediafire.com/file/b7ryynynbzpdy2q/Save0001.sav
