### ISSUE TITLE
blps save editor error code, exception was thrown

### ISSUE THREAD

**Issue by djagaimo** [gibbed/Gibbed.BorderlandsOz#22]
error code brought up when loading in xbox 360 .sav files onto the blps save editor

---------------------------
Error
---------------------------
An exception was thrown (press Ctrl+C to copy):

ProtoBuf.ProtoException: Invalid wire-type; this usually means you have over-written a file without truncating or setting the length; see http://stackoverflow.com/q/2152978/23354

   at ProtoBuf.ProtoReader.StartSubItem(ProtoReader reader)

   at ProtoBuf.ProtoReader.ReadTypedObject(Object value, Int32 key, ProtoReader reader, Type type)

   at proto_2(Object , ProtoReader )

   at ProtoBuf.Meta.TypeModel.DeserializeCore(ProtoReader reader, Type type, Object value, Boolean noAutoCreate)

   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context)

   at ProtoBuf.Serializer.Deserialize[T](Stream source)

   at Gibbed.BorderlandsOz.FileFormats.SaveFile.Deserialize(Stream input, Platform platform, DeserializeSettings settings)

   at Gibbed.BorderlandsOz.SaveEdit.ShellViewModel.<>c__DisplayClass58_0.<ReadSave>b__2()

   at Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context)
---------------------------
OK   
---------------------------

if anyone can help me figure out how to resolve this, that would be dope 

^^

**Comment by gibbed** [comment]
1. Ensure you have [the latest release](https://github.com/gibbed/Gibbed.BorderlandsOz/releases/latest).
1. If you have the latest release and are still receiving this error, attach the save file causing the error to this issue.

**Comment by djagaimo** [comment]
dl'd bloz saveedit ver 1.0.2 and the exception was thrown code still showed up. also even used horizon to extract the 360 .sav file and the error still showed up.

save file is right here, and exception was thrown error is down below.sav file. let me know if you will need anything else from me, and i will do my best to send it to you asap.

[SaveGame.zip](https://github.com/gibbed/Gibbed.BorderlandsOz/files/3110777/SaveGame.zip)


---------------------------
Error
---------------------------
An exception was thrown (press Ctrl+C to copy):

ProtoBuf.ProtoException: Invalid wire-type; this usually means you have over-written a file without truncating or setting the length; see http://stackoverflow.com/q/2152978/23354

   at ProtoBuf.ProtoReader.StartSubItem(ProtoReader reader)

   at ProtoBuf.ProtoReader.ReadTypedObject(Object value, Int32 key, ProtoReader reader, Type type)

   at proto_2(Object , ProtoReader )

   at ProtoBuf.Meta.TypeModel.DeserializeCore(ProtoReader reader, Type type, Object value, Boolean noAutoCreate)

   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context)

   at ProtoBuf.Serializer.Deserialize[T](Stream source)

   at Gibbed.BorderlandsOz.FileFormats.SaveFile.Deserialize(Stream input, Platform platform, DeserializeSettings settings)

   at Gibbed.BorderlandsOz.SaveEdit.ShellViewModel.<>c__DisplayClass58_0.<ReadSave>b__2()

   at Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context)
---------------------------
OK   
---------------------------

<3

**Comment by DeathReaperG** [comment]
Gibbed, I have the newest one and everything like that, also tried every system quick fixes I could do. Save wizard redid it so it's not coded numbers like the other games in it. I was told on another foreman that's the problem....is that true?  Is there a way around it?
