### ISSUE TITLE
can't open the save file

### ISSUE THREAD

**Issue by prosidom107** [gibbed/Gibbed.BorderlandsOz#29]
---------------------------
Error
---------------------------
An exception was thrown (press Ctrl+C to copy):

ProtoBuf.ProtoException: Invalid wire-type; this usually means you have over-written a file without truncating or setting the length; see http://stackoverflow.com/q/2152978/23354

   at ProtoBuf.ProtoReader.StartSubItem(ProtoReader reader)

   at ProtoBuf.ProtoReader.ReadTypedObject(Object value, Int32 key, ProtoReader reader, Type type)

   at proto_2(Object , ProtoReader )

   at ProtoBuf.Meta.TypeModel.DeserializeCore(ProtoReader reader, Type type, Object value, Boolean noAutoCreate)

   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context)

   at ProtoBuf.Serializer.Deserialize[T](Stream source)

   at Gibbed.BorderlandsOz.FileFormats.SaveFile.Deserialize(Stream input, Platform platform, DeserializeSettings settings)

   at Gibbed.BorderlandsOz.SaveEdit.ShellViewModel.<>c__DisplayClass58_0.<ReadSave>b__0()

   at Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context)
---------------------------
OK   
---------------------------
[Save0004.zip](https://github.com/gibbed/Gibbed.BorderlandsOz/files/3284091/Save0004.zip)

**Comment by prosidom107** [comment]
i'm sorry, i'm download the wrong version
