### ISSUE TITLE
pre sequel an error was thrown

### ISSUE THREAD

**Issue by tdjohnny** [gibbed/Gibbed.BorderlandsOz#31]
sorry about posting same issue but no matter what site i looked for help on idk how to fix this when i first loaded up the pre-sequel editor it worked then i clicked on the save icon then save as after and clicked the same slot as my only character then the next time i tried to edit it this happend. I tried lookin at the post on april 21st but couldnt figure out the problem i was having.

---------------------------
Error
---------------------------
An exception was thrown (press Ctrl+C to copy):

Gibbed.BorderlandsOz.GameInfo.ResourceNotFoundException: item type 'GD_Cork_ClassMods_SMJ.A_Item_Gladiator.ClassMod_Gladiator_Blademaster' is not valid for 'GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_06_EridianVanquisher'

   at Gibbed.BorderlandsOz.GameInfo.ItemBalanceDefinition.Create(ItemDefinition item)

   at Gibbed.BorderlandsOz.SaveEdit.BaseItemViewModel.BuildPartAssets()

   at Gibbed.BorderlandsOz.SaveEdit.BaseItemViewModel.BuildBalanceAssets()

   at Gibbed.BorderlandsOz.SaveEdit.BaseItemViewModel..ctor(BaseItem item)

   at Gibbed.BorderlandsOz.SaveEdit.BackpackItemViewModel..ctor(BackpackItem item)

   at Gibbed.BorderlandsOz.SaveEdit.BackpackViewModel.ImportData(WillowTwoPlayerSaveGame saveGame, Platform platform)

   at Gibbed.BorderlandsOz.SaveEdit.ShellViewModel.<>c__DisplayClass62_0.<ReadSave>b__0()

   at Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context)
---------------------------
OK   
---------------------------

**Comment by gibbed** [comment]
1. Please ensure you have the [latest release](https://github.com/gibbed/Gibbed.BorderlandsOz/releases/latest).
1. If you're still having the issue, please attach the save with the problem to this issue as a comment.

**Comment by tdjohnny** [comment]
I have the latest issue, I tried deleting and reinstalling a few times. when i try to add the save file it says it doesn't accept the file type, how can I use winrar to zip it and put it in here?

**Comment by gibbed** [comment]
Yes, you can do that.

**Comment by tdjohnny** [comment]
[Save0001.zip](https://github.com/gibbed/Gibbed.BorderlandsOz/files/3319119/Save0001.zip)

i think this is the correct file Im not the best at this stuff sorry. My borderlands 2 gibbed editor had no issues at all between all the characters I used it on.

**Comment by gibbed** [comment]
Grab the new [1.0.25 release](https://github.com/gibbed/Gibbed.BorderlandsOz/releases/latest) (or newer) which has a fix for this problem.

**Comment by tdjohnny** [comment]
thanks alot for your help and for fixing it so quick.
