### ISSUE TITLE
Failed to load items causing unusable saves

### ISSUE THREAD

**Issue by xcier** [gibbed/Gibbed.BorderlandsOz#36]
Gibbed.BorderlandsOz.GameInfo.ResourceNotFoundException: item type 'GD_Cork_ClassMods_TW.A_Item_Prototype.ClassMod_Prototype_ShortCircuit' is not valid for 'GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_05_Legendary'

   at Gibbed.BorderlandsOz.GameInfo.ItemBalanceDefinition.Create(ItemDefinition item)

   at Gibbed.BorderlandsOz.SaveEdit.BaseItemViewModel.BuildPartAssets()

   at Gibbed.BorderlandsOz.SaveEdit.BaseItemViewModel..ctor(BaseItem item)

   at Gibbed.BorderlandsOz.SaveEdit.BackpackItemViewModel..ctor(BackpackItem item)

   at Gibbed.BorderlandsOz.SaveEdit.BackpackViewModel.ImportData(WillowTwoPlayerSaveGame saveGame, Platform platform)

   at Gibbed.BorderlandsOz.SaveEdit.ShellViewModel.<>c__DisplayClass62_0.<ReadSave>b__0()

   at Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context)

Again with borderlands 2 gibbed no idea when this issue started it was just told to me one of my saves was showing as corrupt and went to fix it when i run in to this error

**Comment by gibbed** [comment]
Please attach a sample save file that has this issue, decrypted if it's a console save.

**Comment by xcier** [comment]
[SaveDROP.zip](https://github.com/gibbed/Gibbed.BorderlandsOz/files/4052122/SaveDROP.zip)
