### ISSUE TITLE
Can't find the issue in the save nor can parse it to look at it. 

### ISSUE THREAD

**Issue by xcier** [gibbed/Gibbed.BorderlandsOz#37]
---------------------------
Error
---------------------------
An exception was thrown (press Ctrl+C to copy):

System.ArgumentException: count exceeds buffer bounds

   at ICSharpCode.SharpZipLib.Zip.Compression.Inflater.Inflate(Byte[] buffer, Int32 offset, Int32 count)

   at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.Read(Byte[] buffer, Int32 offset, Int32 count)

   at Gibbed.BorderlandsOz.FileFormats.SaveFile.Deserialize(Stream input, Platform platform, DeserializeSettings settings)

   at Gibbed.BorderlandsOz.SaveEdit.ShellViewModel.<>c__DisplayClass58_0.<ReadSave>b__2()

   at Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context)
---------------------------
OK   
---------------------------

Getting a cStringIO error when I try to parse the save, but other saves are parsing just fine.
![Save0001](https://user-images.githubusercontent.com/36747898/78583811-f0954600-77fc-11ea-8be8-129d39e1dd79.png)

**Comment by gibbed** [comment]
Can you attach a copy of the save?

**Comment by xcier** [comment]
https://www.mediafire.com/file/sdf3eku6jtle7jv/Nisha.zip/file
