### ISSUE TITLE
Editing PS4 save 10/7/2020

### ISSUE THREAD

**Issue by Echosoft999** [gibbed/Gibbed.BorderlandsOz#39]
Using: Save Wizard PS4 MAX, .bat files to convert ps4 to xbox360 and xbox360 to ps4 save, Gibbed.Borderlands2.SaveEdit (1.0.46)

After exporting from save wizard, and converting with the first .bat file I try to open in Gibbed. Gibbed throws the following error:

ProtoBuf.ProtoException: Invalid wire-type; this usually means you have over-written a file without truncating or setting the length; see https://stackoverflow.com/q/2152978/23354

   at ProtoBuf.ProtoReader.AppendBytes(Byte[] value, ProtoReader reader)

   at proto_2(Object , ProtoReader )

   at ProtoBuf.Meta.TypeModel.DeserializeCore(ProtoReader reader, Type type, Object value, Boolean noAutoCreate)

   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context)

   at ProtoBuf.Serializer.Deserialize[T](Stream source)

   at Gibbed.Borderlands2.FileFormats.SaveFile.Deserialize(Stream input, Platform platform, DeserializeSettings settings)

   at Gibbed.Borderlands2.SaveEdit.ShellViewModel.<>c__DisplayClass62_0.<ReadSave>b__0()

   at Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context)

I am not sure what I am supposed to do from here. I have tried different versions of Gibbed but that doesn't seem to change anything.

**Comment by xcier** [comment]
SW uses their own serialization as of late 2019
