### ISSUE TITLE
Problems opening a save file (PC)

### ISSUE THREAD

**Issue by KurtCobain1994** [gibbed/Gibbed.BorderlandsOz#5]
whenever i try to open a save file it will say this:

---------------------------
Error
---------------------------
An exception was thrown (press Ctrl+C to copy):

ProtoBuf.ProtoException: Invalid wire-type; this usually means you have over-written a file without truncating or setting the length; see http://stackoverflow.com/q/2152978/23354

   at ProtoBuf.ProtoReader.StartSubItem(ProtoReader reader)

   at ProtoBuf.ProtoReader.ReadTypedObject(Object value, Int32 key, ProtoReader reader, Type type)

   at proto_2(Object , ProtoReader )

   at ProtoBuf.Meta.TypeModel.DeserializeCore(ProtoReader reader, Type type, Object value, Boolean noAutoCreate)

   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context)

   at ProtoBuf.Serializer.Deserialize[T](Stream source)

   at Gibbed.BorderlandsOz.FileFormats.SaveFile.Deserialize(Stream input, Platform platform, DeserializeSettings settings)

   at Gibbed.BorderlandsOz.SaveEdit.ShellViewModel.<>c__DisplayClass58_0.<ReadSave>b__2()

   at Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context)
---------------------------
OK   
---------------------------

**Comment by gibbed** [comment]
Please attach a copy of the save file to this issue.

**Comment by KurtCobain1994** [comment]
Yes, ofcourse! ,


Thanks in advance!
[Save0002.zip](https://github.com/gibbed/Gibbed.BorderlandsOz/files/1507939/Save0002.zip)

**Comment by gibbed** [comment]
That's a Borderlands 2 save file.

**Comment by gibbed** [comment]
https://github.com/gibbed/Gibbed.Borderlands2
